# Generated by Django 2.2 on 2021-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211124_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(default=None, to='mainapp.ProductCategory'),
        ),
    ]
