# Generated by Django 3.2.9 on 2021-11-27 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('mainapp', '0003_auto_20211127_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='site',
            field=models.ManyToManyField(null=True, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='site',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='sites.site'),
        ),
    ]
